###########
# Kafka Connect
###########

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-connect-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Create
    # Debezium topics
    - resource:
        type: cluster
        name: kafka-cluster
      operation: Create
    - resource:
        type: cluster
        name: kafka-cluster
      operation: DescribeConfigs
    - resource:
        type: topic
        name: dbserver
        patternType: prefix
      operation: Describe
    - resource:
        type: topic
        name: dbserver
        patternType: prefix
      operation: Write
    - resource:
        type: topic
        name: dbserver
        patternType: prefix
      operation: Read
    - resource:
        type: topic
        name: dbserver
        patternType: prefix
      operation: Create
    - resource:
        type: topic
        name: schema-changes.inventory
      operation: Describe
    - resource:
        type: topic
        name: schema-changes.inventory
      operation: Write
    - resource:
        type: topic
        name: schema-changes.inventory
      operation: Read
    - resource:
        type: topic
        name: schema-changes.inventory
      operation: Create
---

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  image: quay.io/scholzj/demo-kafka-and-its-friends-2019:kafka-connect-debezium-cdc
  version: 2.2.1
  replicas: 1
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 250m
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
    - secretName: my-cluster-cluster-ca-cert
      certificate: ca.crt
  metrics:
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_connect_metrics_$1_$2"
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-connect-cluster
      certificate: user.crt
      key: user.key
  jvmOptions:
    gcLoggingEnabled: false
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  port:
    targetPort: rest-api
  to:
    kind: Service
    name: my-connect-cluster-connect-api
---
