apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: email-and-address
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: email-and-address
      operation: Describe
    - resource:
        type: topic
        name: email-and-address
      operation: Read
    - resource:
        type: group
        name: email-and-address
        patternType: prefix
      operation: Read
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: email-and-address
  name: email-and-address
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email-and-address
    spec:
      containers:
      - name: cdc-demo-watcher
        image: quay.io/scholzj/demo-kafka-and-its-friends-2019:email-and-address
        imagePullPolicy: IfNotPresent
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: email-and-address
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: email-and-address
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: email-and-address
          - name: GROUP_ID
            value: email-and-address